import type { Metadata } from "next";
import { DM_Sans as fontSans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar";

const dmSans = fontSans({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased font-sans`}>
        <Navbar />
        <div className="min-h-[calc(100vh-56px)] mt-14 w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
